CREATE TABLE messages (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	message VARCHAR NOT NULL,
	sleep_time INTEGER NOT NULL
, status VARCHAR NOT NULL DEFAULT "Queued", message_id VARCHAR NOT NULL);